login and logout with respective tests
octo-web-front-end-tribe/microblog-react pull request #3
Opened 2017-04-05 21:03 UTC by rquelen

2017-04-06 08:55 UTC, trollepierre reviewed
ça me va !
(après relecture du code, uniquement)

2017-04-06 08:55 UTC, trollepierre commented on src/AuthenticatedRoute/AuthenticatedRoute.spec.js
> +        // given
// to delete

2017-04-06 21:28 UTC, pierrettebertrand requested changes
2 petits changements.
Sinon c'est top merci Roman !

2017-04-06 21:28 UTC, pierrettebertrand commented on src/LoginForm/LoginForm.js
> +      this.authenticate();
Il manque la redirection vers la page appelante :)

Ce que tu peux faire en gérant un state dans le composant (qui part défault est à false, et que tu passes  à true à la fin de la méthode authenticate.)

Comme setState va provoquer un render tu peux mettre un if dans le render tel que :
```
if(this.state.authenticated) {
      return (<Redirect to="..."/>);
    }
```

Faudrait qu'on trouve un moyen de récupérer l'appelant d'une façon clean :)

2017-04-06 21:28 UTC, pierrettebertrand commented on src/LoginForm/LoginForm.js
> +    window.localStorage.setItem('name', this.state.inputValue);
Je te propose de faire un utilitaire de login / logout.

Comme ça on cache la complexité de l'implémentation, c'est plus facile à tester, ça rend le code plus explicite.

Et ça évite les régressions si on change la clé dans le local storage (on n'aura pas besoin de la changer de partout)

2017-04-14 13:41 UTC, rquelen commented on src/LoginForm/LoginForm.js
> +      this.authenticate();
c'est fait, par contre on retourne toujours sur home

2017-04-14 13:53 UTC, rquelen commented on src/AuthenticatedRoute/AuthenticatedRoute.spec.js
> +        // given
ok

2017-04-21 12:45 UTC, merged